export const EMAIL_CHANGED = 'email_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_SUCCESS_TOKEN = 'login_user_success_token';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER = 'login_user';
export const EMPLOYEE_UPDATE = 'employee_update';
export const UTIPAY_COUNTRIES = 'utipay_countries';
export const UTIPAY_COUNTRIES_SUCCESS = 'utipay_countries_success';
export const UTIPAY_COUNTRIES_FAIL ='utipay_countries_fail';
export const UTIPAY_COUNTRY_UPDATE = 'utipay_country_update';
export const UTIPAY_COUNTRY_CREATE_SUCCESS = 'utipay_country_create_success';
export const UTIPAY_COUNTRIES_LOADING = 'utipay_countries_loading';
export const UTIPAY_COUNTRY_INITIAL_STATE = 'utipay_country_initial_state'
